include:
  - ./pkmn-config-server/config-server-compose.yaml
  - ./pkmn-authorization-server/authorization-server-compose.yaml
  - ./pkmn-main-app/main-app-compose.yaml
  - ./pkmn-rest-api/rest-api-compose.yaml
services:
  pkmn-database:
    image: postgres:17.2-alpine
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - pkmn-database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pkmn_user
      POSTGRES_PASSWORD: pkmn_password
      POSTGRES_DB: pkmn_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - pkmn-net

  pkmn-redis:
    image: redis:7.4.1
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - pkmn-redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - pkmn-net
volumes:
  pkmn-database_data:
  pkmn-db-migrations:
  pkmn-redis_data:
  pkmn-config-repo:

networks:
  pkmn-net:
    ipam:
      config:
        - subnet: 172.16.0.0/23
          ip_range: 172.16.0.0/24
